config/routes.rb
FinishMySideProject2::Application.routes.draw do
  resources :endorsements

  get "admin/index"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :side_projects do
    resources :comments
  end

  get "public/fonts"

  get "assets/fonts", as: 'fonts'

  get "home/index", as: 'index'

  get "home/about", as: 'about'

  get "home/terms_of_use", as: 'terms'

  get "home/privacy_policy", as: 'privacy'

  get "users/new"

  get "users/show"

  get "home/endorse", as: 'endorse'

  match '/users/:id', :to => 'users#show', :as => :user
  match '/tags/:id', :to => 'tags#index', :as => :tag

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :side_project
  attr_accessible :body, :commenter, :side_project

  validates :body, :presence => true
end

app/models/side_project.rb
class SideProject < ActiveRecord::Base

  attr_accessible :description, :image_url, :project_title, :side_project_id, :user, :repo_url, :tags_attributes

  validates :description, :image_url, :project_title, :presence => true
  validates :project_title, :uniqueness =>  true

  has_many :comments, :dependent => :destroy
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :endorsers
  belongs_to :user



  accepts_nested_attributes_for :tags, :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :side_projects
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :name, :password_digest, :password, :password_confirmation, :email, :profile_pic

  has_many :side_projects
  has_and_belongs_to_many :endorsements

  validates :name, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true

  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @last_project = SideProject.last
    @last_comment = Comment.last
    @last_user = User.last
    @total_projects = SideProject.count
    @total_comments = Comment.count
    @total_users = User.count
    #@total_sessions = Session.count
    @user = User.find_by_id(session[:user_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

before_filter :authorize
 @time = Time.now.year

  protected

    def authorize
      unless User.find_by_id(session[:user_id])
        redirect_to login_url, alert: "Please log in"
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  skip_before_filter :authorize

  def create
    @side_project = SideProject.find(params[:side_project_id])
    @commenter = Session.find(session[:user_id])
    @comment = @side_project.comments.create(params[:comment])

    redirect_to side_project_path(@side_project)
  end

  def destroy
    @side_project = SideProject.find(params[:side_project_id])
    @comment = @side_project.comments.find(params[:id])
    @comment.destroy
    redirect_to side_project_path(@side_project)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_before_filter :authorize, only: [:index, :terms_of_use, :privacy_policy, :about]

  def index
    @side_projects = SideProject.paginate page: params[:page], order: 'created_at desc', per_page: 4
    #@id = 125.to_i
    @side_project = SideProject.first
    #{ @comment = Comment.find(params[:id])}
    #respond_to do |format|
      #format.html # show.html.erb
      #format.json { render json: @side_project }
      render :template => 'home/index.html.erb'
      #format.json { render json: @side_projects }
    #end



    #@featured_project = SideProject.first(1)
      #respond_to do |format|
        #render :template => 'home/index.html.erb'
        #format.json { render json: @side_projects }
      #end


  end

  def about
  end

  def terms_of_use
  end

  def privacy_policy
  end

  def side_project
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :authorize

  def new
  end

  def create
     user = User.find_by_name(params[:name])
     if user and user.authenticate(params[:password])
       session[:user_id] = user.id
       redirect_to user_path(user), alert: "Welcome!"
     else
       redirect_to login_url, alert: "Invalid user/password combination"
     end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, alert: "Logged out"
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_filter :authorize, only: [:index]
  def index
    #@tags = Tag.all()
    @tag = Tag.find(params[:id])
    @tags = Tag.paginate page: params[:page], order: 'created_at desc', per_page: 5
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json

  skip_before_filter :authorize


  def index
    @users = User.order(:name)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url,
          notice: "User #{@user.name} was successfully created."}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: "User #{@user.name} successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/side_projects_helper.rb
module SideProjectsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>

<h1>
  Welcome <%= @user.name %>
</h1>

<% if flash[:alert] %>
    <p id="notice"><%= flash[:alert] %></p>
<% end %>

<p>
  It's <%= Time.now %><br />
  We have <%= pluralize(@total_comments, 'new comment') %>. Last comment created at <%= @last_comment.created_at %> <br />
  We have <%= pluralize(@total_projects, 'new project') %>. Last updated at <%= @last_project.updated_at %><br />
  We have <%= pluralize(@total_users, 'new user') %>. Last user created at <%= @last_user.created_at %><br />
</p>

<p>
  Admin tools:<br />
  <%= link_to "Edit Home", home_index_path %>
  <%= link_to "Edit About", home_about_path %>
  <%= link_to "Approve/Reject Side Projects", side_projects_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finish My Side Project</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <div class="greenArrow">
    <%= image_tag("greenArrow.png") %>
  </div>
  <div id="topLinks">
    <%= link_to "About", about_path %>
    <%= link_to "Terms of Use", terms_path %>
    <%= link_to "privacy policy", privacy_path %>
    <%= link_to "- Login -", login_path %>
  </div>
  <div class="siteTitle">
    <%= link_to "FinishMySideProject.com", index_path %>
  </div>
  <div class="bottomLinks">
    <%= link_to "Browse", side_projects_path %>
    <%= link_to "submit", new_side_project_path %>
  </div>
  <div id="headerBackground">
  </div>
  <div class="redArrow">
    <%= image_tag("redArrow.png") %>
  </div>
</header>

<div id="siteContainer">
  <%= yield %>
</div>


<footer>
  <div id="footerLinks">
    <%= link_to "Terms of Use", terms_path %>
    <%= link_to "Our Privacy Policy", privacy_path %>
    <%= link_to "Admin", admin_path() %>
    <p>© Freckle Interactive, LLC <%= Time.now.year %></p>
  </div>
</footer>

</body>

</html>