config/routes.rb
FinishMySideProject2::Application.routes.draw do
  resources :endorsements

  get "admin/index"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :side_projects do
    resources :comments
  end

  get "public/fonts"

  get "assets/fonts", as: 'fonts'

  get "home/index", as: 'index'

  get "home/about", as: 'about'

  get "home/terms_of_use", as: 'terms'

  get "home/privacy_policy", as: 'privacy'

  get "users/new"

  get "users/show"

  get "home/endorse", as: 'endorse'

  match '/users/:id', :to => 'users#show', :as => :user
  match '/tags/:id', :to => 'tags#index', :as => :tag

  root :to => 'home#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :side_projects
  attr_accessible :name
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_filter :authorize, only: [:index]
  def index
    #@tags = Tag.all()
    @tag = Tag.find(params[:id])
    @tags = Tag.paginate page: params[:page], order: 'created_at desc', per_page: 5
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form.fields_for :tags do |tag_form| %>
    <div class="field">
      <%= tag_form.label :name, 'Tag:' %>
      <%= tag_form.text_field :name %>
    </div>
    <% unless tag_form.object.nil? || tag_form.object.new_record? %>
        <div class="field">
          <%= tag_form.label :_destroy, 'Remove:' %>
          <%= tag_form.check_box :_destroy %>
        </div>
    <% end %>
<% end %>

app/views/tags/_list.html.erb
<div class="projectsContainer">
  <% @tag.side_projects.each do |side_project| %>
      <div class="descriptionContainer shadow">
        <h3><%= link_to side_project.project_title, side_project %></h3>

        <p><%= truncate(side_project.description, length: 200) %></p>
        <%= image_tag(side_project.image_url, class: 'list_image') %>
        <%= button_to side_project.repo_url, side_project.user %>
        <div class="descriptionButtons">
          <%= button_to 'Email Owner', side_project.user %>
          <!--  #button_to 'Edit', edit_side_project_path(side_project) %> edit needs to be made admin and/or owner only -->
          <!--  #button_to 'Destroy', side_project, confirm: 'Are you sure?', method: :delete %> destroy  needs to be made admin and/or owner only -->
          <%= button_to 'Endorse Project', endorse_path %>
        </div>

      </div>
  <% end %>
</div>

app/views/tags/index.html.erb
<h1>Other projects tagged '<%= @tag.name %>':</h1>



<div class="paginate"><%= will_paginate @tags, :class =>"pagination" %></div>

<%= render :partial => 'tags/list' %>