config/routes.rb
FinishMySideProject2::Application.routes.draw do
  resources :endorsements

  get "admin/index"

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'logout' => :destroy
  end

  resources :users

  resources :side_projects do
    resources :comments
  end

  get "public/fonts"

  get "assets/fonts", as: 'fonts'

  get "home/index", as: 'index'

  get "home/about", as: 'about'

  get "home/terms_of_use", as: 'terms'

  get "home/privacy_policy", as: 'privacy'

  get "users/new"

  get "users/show"

  get "home/endorse", as: 'endorse'

  match '/users/:id', :to => 'users#show', :as => :user
  match '/tags/:id', :to => 'tags#index', :as => :tag

  root :to => 'home#index'

end

app/models/side_project.rb
class SideProject < ActiveRecord::Base

  attr_accessible :description, :image_url, :project_title, :side_project_id, :user, :repo_url, :tags_attributes

  validates :description, :image_url, :project_title, :presence => true
  validates :project_title, :uniqueness =>  true

  has_many :comments, :dependent => :destroy
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :endorsers
  belongs_to :user



  accepts_nested_attributes_for :tags, :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

end

app/controllers/side_projects_controller.rb
class SideProjectsController < ApplicationController

  skip_before_filter :authorize, only: [:index, :show]

  #http_basic_authenticate_with :name => "Zack", :password => "secret", :except => [:index, :show]

  # GET /side_projects
  # GET /side_projects.json
  def index

    @side_projects = SideProject.paginate page: params[:page], order: 'created_at desc', per_page: 10
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @side_projects }
    end
  end

  # GET /side_projects/1
  # GET /side_projects/1.json
  def show
    @endorsement = Endorsement.find_by_side_project_id(params[:id])
    @endorser = User.find(@endorsement)
    @side_project = SideProject.find(params[:id])
   #{ @comment = Comment.find(params[:id])}
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @side_project }
    end

  end

  # GET /side_projects/new
  # GET /side_projects/new.json
  def new
    @side_project = SideProject.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @side_project }
    end
  end

  # GET /side_projects/1/edit
  def edit
    @side_project = SideProject.find(params[:id])
  end

  # POST /side_projects
  # POST /side_projects.json
  def create
    @side_project = SideProject.new(params[:side_project])
    @side_project.user = User.find(session[:user_id])

    respond_to do |format|
      if @side_project.save
        format.html { redirect_to @side_project, notice: 'Side project was successfully created.' }
        format.json { render json: @side_project, status: :created, location: @side_project }
      else
        format.html { render action: "new" }
        format.json { render json: @side_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /side_projects/1
  # PUT /side_projects/1.json
  def update
    @side_project = SideProject.find(params[:id])

    respond_to do |format|
      if @side_project.update_attributes(params[:side_project])
        format.html { redirect_to @side_project, notice: 'Side project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @side_project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /side_projects/1
  # DELETE /side_projects/1.json
  def destroy
    @side_project = SideProject.find(params[:id])
    @side_project.destroy

    respond_to do |format|
      format.html { redirect_to side_projects_url }
      format.json { head :no_content }
    end
  end

  def comment

  end

  def user
  end

  def endorse


  end


end

app/helpers/side_projects_helper.rb
module SideProjectsHelper
end

app/views/side_projects/_form.html.erb
<% @side_project.tags.build %>
<%= form_for(@side_project) do |project_form| %>
  <% if @side_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@side_project.errors.count, "error") %> prohibited this side_project from being saved:</h2>

      <ul>
      <% @side_project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h2><%= project_form.label :project_title %><br /> </h2>
    <%= project_form.text_field :project_title %>
  </div>
  <div class="field">
    <h2><%= project_form.label :description %><br /> </h2>
    <%= project_form.text_area :description %>
  </div>
  <div class="field">
    <h2><%= project_form.label :image_url %><br /> </h2>
    <%= project_form.text_field :image_url %>
  </div>
  <div class="field">
    <h2><%= project_form.label :repo_url %><br /> </h2>
    <%= project_form.text_field :repo_url %>
  </div>
  <h2>Tags</h2>
    <%= render :partial => 'tags/form',
                :locals => {:form => project_form}%>
  <div class="actions">
    <%= project_form.submit %>
  </div>


<% end %>

app/views/side_projects/_list.html.erb
<div class="projectsContainer">
  <% @side_projects.each do |side_project| %>
      <div class="descriptionContainer shadow">
          <h3><%= link_to side_project.project_title, side_project %></h3>

          <p><%= truncate(side_project.description, length: 200) %></p>
          <%= image_tag(side_project.image_url, class: 'list_image') %>
          <%= button_to side_project.repo_url, side_project.user, {:class => 'buttonTo'} %>
            <%= button_to 'Email Owner', side_project.user, {:class => 'buttonTo'} %>
            <!--  #button_to 'Edit',  %> edit needs to be made admin and/or owner only -->
            <!--  #button_to 'Destroy', side_project, confirm: 'Are you sure?', method: :delete %> destroy  needs to be made admin and/or owner only -->
            <%= button_to 'Endorse Project', endorse_path, {:class => 'buttonTo'}%>


      </div>
  <% end %>
</div>

app/views/side_projects/edit.html.erb
<h1>Editing side_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @side_project %> |
<%= link_to 'Back', side_projects_path %>

app/views/side_projects/index.html.erb
<div id="siteContainer">

  <h1>Browse Side Projects</h1>

  <%= render :partial => 'side_projects/list' %>

</div>

app/views/side_projects/new.html.erb
<h1>Tell us about your project!</h1>

<%= render 'form' %>

<%= link_to 'Back', side_projects_path %>

app/views/side_projects/show.html.erb
<p id="notice"><%= notice %></p>


<div class="projectDetails">

<h1>
  <b>Project title:</b>
  <%= @side_project.project_title %>
</h1>

  <h2>Tags:
    <% @side_project.tags.each do |tag| %>
        <div class="tagButton"><%= button_to tag.name, tag %></div>
    <% end %>
  </h2>

<div class="imageShow">
  <%= image_tag(@side_project.image_url, class: 'list_image') %>
</div>

<h2>Owner:</h2>
  <%= @side_project.user.name %>
  <%= image_tag(@side_project.user.profile_pic, class: 'list_image') %>

<h2>Description:</h2>
<p><%= @side_project.description %></p>

 <h2>Repo URL:</h2>
  <button><%= @side_project.repo_url %></button>

  <h2>Endorsed by:</h2>
  <%=  button_to @endorser.name, endorsement_path %> <br/>
  <%=  @endorser.profile_pic %>

  <%= button_to "Endorse This Project", new_endorsement_path %>


<h2>Comments</h2>
<!--also, include a way for the viewer to edit comments-->
<% @side_project.comments.each do |comment| %>
    <p>
      <b>Commenter:</b>
      <%= comment.commenter %>
    </p>

    <p>
      <b>Comment:</b>
      <%= comment.body %>
    </p>

    <p>
      <b>Created:</b>
      <%= comment.created_at %>
    </p>



<% end %>
<%= render 'comments/comment' %>




<%= link_to 'Back', side_projects_path %>
<!-- back functionality is broken site-wide -->

</div>